### ISSUE TITLE
Use pre-compiled deb?

### ISSUE THREAD

**Issue by benarent** [PaulVMo/helium-validator-deb#1]
Hi @PaulVMo,

Firstly thanks for creating this. I've been planning something like this myself, but using the pre-compiled .debs from Helium https://packagecloud.io/helium/validators . There doesn't seem to be any extra sauce added in `build_deb.sh` so, would it be better to recommend these packages?

**Comment by PaulVMo** [comment]
Thanks for your question Ben. The current deb package on packagecloud was
created by the core dev for a specific use - running unstaked validators to
support data only hotspots.

I identified a number of enhancements to make the package more friendly to
validator operators and have included those in my build_deb script. For
example,
- includes the genesis block rather than requiring it to be loaded manually
after install
- sets the validator service to run automatically after install
- runs the service as its own user which is created by the install; the
helium one assumes the user 'ubuntu' which may or may not exist
- places files in more standard locations

I have submitted these changes as a PR to the core helium repo which is
still pending. In the meantime, I offer this as a more user friendly
alternative.

Lastly, in the spirit of decentralization, it's always good to have more
options of builds.

This repo is open source. Feel free to use parts if you wish.
